branch-defaults:
  master:
    environment: Memona-env
environment-defaults:
  Memona-env:
    branch: null
    repository: null
global:
  application_name: memona
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
